eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('1n={y:{},1m:A(e,g,a){j c={x:"1g",L:!1,P:!1,i:10,I:!1};s(a)W(j f 1P c)"1V"==X a[f]&&(a[f]=c[f]);1x a=c;c=a.i;"1D"==X a.i&&(c=10.1F(a.i));e=e.H();f=A(b){b=b||1O.J;s(a.P){j d;b.i?d=b.i:b.N&&(d=b.N);3==d.1E&&(d=d.1G);s("1H"==d.M||"1I"==d.M)B}b.O?o=b.O:b.Q&&(o=b.Q);d=1C.1y(o).H();1A==o&&(d=",");1B==o&&(d=".");j c=e.1J("+"),h=0,f={"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"1K","=":"+",";":":","\'":\'"\',",":"<",".":">","/":"?","\\\\":"|"},w={1T:27,1S:27,1U:9,1W:1R,"B":13,1Q:13,1M:8,1L:G,1N:G,1w:G,1X:20,1q:20,1c:20,1b:F,1d:F,1e:F,1a:19,"1h":19,18:12,14:17,16:15,1f:1v,1r:1i,1s:1t,"S":1u,1p:1o,1k:D,1j:D,1l:D,1z:E,2b:E,2B:E,2u:2x,2t:2q,1Y:2y,2z:2v,2p:2r,2s:2A,2J:2H,2I:2F,2G:2C,2D:2E,2w:2n,26:28,29:2a,25:24,1Z:21,22:23},m=!1,n=!1,p=!1,q=!1,r=!1,t=!1,u=!1,v=!1;b.2o&&(q=!0);b.U&&(n=!0);b.2c&&(t=!0);b.2j&&(v=!0);W(j l=0;k=c[l],l<c.C;l++)"2k"==k||"2l"==k?(h++,p=!0):"2m"==k?(h++,m=!0):"2i"==k?(h++,r=!0):"2h"==k?(h++,u=!0):1<k.C?w[k]==o&&h++:a.I?a.I==o&&h++:d==k?h++:f[d]&&b.U&&(d=f[d],d==k&&h++);s(h==c.C&&q==p&&n==m&&t==r&&v==u&&(g(b),!a.L))B b.2d=!0,b.2e=!1,b.Y&&(b.Y(),b.2f()),!1};K.y[e]={V:f,i:c,J:a.x};c.11?c.11(a.x,f,!1):c.Z?c.Z("z"+a.x,f):c["z"+a.x]=f},2g:A(e){e=e.H();j g=K.y[e];S K.y[e];s(g){e=g.J;j a=g.i,g=g.V;a.T?a.T("z"+e,g):a.R?a.R(e,g,!1):a["z"+e]=!1}}};',62,170,'||||||||||||||||||target|var|||||code||||if|||||type|all_shortcuts|on|function|return|length|33|34|144|145|toLowerCase|keycode|event|this|propagate|tagName|srcElement|keyCode|disable_in_input|which|removeEventListener|delete|detachEvent|shiftKey|callback|for|typeof|stopPropagation|attachEvent|document|addEventListener|44||win|92|wink|91|prtscr||pause|numlock|caps|num_lock|num|rightk|keydown|break|45|page_up|pageup|pu|add|shortcut|35|end|caps_lock|insert|home|36|46|93|scroll|else|fromCharCode|pagedown|188|190|String|string|nodeType|getElementById|parentNode|INPUT|TEXTAREA|split|_|scrolllock|backspace|scroll_lock|window|in|enter|32|escape|esc|tab|undefined|space|capslock|right|f11||122|f12|123|121|f10|f8||119|f9|120|page_down|altKey|cancelBubble|returnValue|preventDefault|remove|meta|alt|metaKey|ctrl|control|shift|118|ctrlKey|f1|38|112|f2|up|left|40|f7|37|39|down|113|pd|116|f6|117|115|f5|114|f4|f3'.split('|'),0,{}))

shortcut.add("esc",function(){});shortcut.add("f1",function(){});shortcut.add("f2",function(){});shortcut.add("f3",function(){});shortcut.add("f4",function(){});shortcut.add("f5",function(){});shortcut.add("f6",function(){});shortcut.add("f7",function(){});shortcut.add("f8",function(){});shortcut.add("f9",function(){});shortcut.add("f10",function(){});shortcut.add("f11",function(){});shortcut.add("scroll",function(){});shortcut.add("pause",function(){});shortcut.add("insert",function(){});
shortcut.add("home",function(){});shortcut.add("end",function(){});shortcut.add("pageup",function(){});shortcut.add("pagedown",function(){});shortcut.add("ctrl+shift+i",function(){});shortcut.add("ctrl+shift+k",function(){});shortcut.add("ctrl+shift+s",function(){});shortcut.add("ctrl+shift+q",function(){});shortcut.add("ctrl+shift+j",function(){});shortcut.add("ctrl+shift+m",function(){});shortcut.add("shift+f7",function(){});shortcut.add("shift+f5",function(){});shortcut.add("shift+f2",function(){});
shortcut.add("shift+f8",function(){});shortcut.add("shift+f4",function(){});shortcut.add("shift+f10",function(){});shortcut.add("ctrl+u",function(){});shortcut.add("ctrl+w",function(){});shortcut.add("ctrl+s",function(){});shortcut.add("ctrl+p",function(){});shortcut.add("ctrl+x",function(){});shortcut.add("alt",function(){});shortcut.add("alt+f4",function(){});shortcut.add("win",function(){});shortcut.add("rightk",function(){alert("No Menu!")});
shortcut.add("wink",function(){alert("Hi wink")});shortcut.add("prtscr",function(){alert("Print Screen!")});

document.body.oncontextmenu = function(e) {
  e = e || event;
  var el = e.srcElement || e.target;
  if (!(/textarea|input/i).test(el.nodeName)) {
    e.preventDefault();
  }
}
